# Generated by Django 2.1.5 on 2019-01-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityperson',
            name='role',
            field=models.CharField(choices=[('leader', 'ผู้นำชุมชน'), ('wise_man', 'ปราชญ์ชุมชน')], default='pending', max_length=10),
        ),
    ]
