# Generated by Django 2.1.5 on 2019-01-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='faith',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='folk_game',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='regional_dialect',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
